pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    stage('Creating dummy folder') {
      steps {
        sh 'mkdir yashas'
      }
    }
  }
}
